name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build frontend Docker image
      run: |
        export TAG=$(date +%s)
        docker build frontend/ --file frontend/Dockerfile --tag frontend:$TAG
        docker save -o frontend-$TAG frontend:$TAG
    - name: Build backend Docker image
      run: |
        docker build backend/ --file backend/Dockerfile --tag backend:$TAG
        docker save -o backend-$TAG backend:$TAG
    - name: Run backend
      run: |
        scp -i $SSH_KEY backend-$TAG ubuntu@150.230.232.20:~/
        ssh -i $SSH_KEY ubuntu@150.230.232.20 "docker import backend-$TAG backend:$TAG; docker run -d -p 80:8080 backend:$TAG; rm backend-$TAG"
    - name: Run frontend
      run: |
        scp -i $SSH_KEY frontend-$TAG ubuntu@129.154.230.82:~/
        ssh -i $SSH_KEY ubuntu@129.154.230.82 "docker import frontend-$TAG frontend:$TAG; docker run -d -p 80:80 frontend:$TAG; rm frontend-$TAG"
    - name: Delete saved Docker images from hosted agent
      run: rm frontend-$TAG backend-$TAG