name: Build and deploy app

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build frontend Docker image
      run: |
        docker build frontend/ --file frontend/Dockerfile --tag frontend
        docker save -o frontend-image.tar frontend
    - name: Build backend Docker image
      run: |
        docker build backend/ --file backend/Dockerfile --tag backend
        docker save -o backend-image.tar backend
    - name: Copy docker image to backend
      uses: appleboy/scp-action@master
      with:
        host: 150.230.232.20
        username: ubuntu
        key: ${{ secrets.SSH_KEY }}
        port: 22
        source: "backend-image.tar"
        target: "~/"
    - name: Copy docker image to frontend
      uses: appleboy/scp-action@master
      with:
        host: 129.154.230.82
        username: ubuntu
        key: ${{ secrets.SSH_KEY }}
        port: 22
        source: "frontend-image.tar"
        target: "~/"
    - name: Run backend
      # env:
      #   SSH_KEY: ${{ secrets.SSH_KEY }}
      uses: appleboy/ssh-action@master
      with:
        host: 150.230.232.20
        username: ubuntu
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: 
          # scp -i $SSH_KEY backend-image ubuntu@150.230.232.20:~/
          docker load < backend-image.tar; docker stop backend; docker rm backend; docker run --name backend -d -p 80:8080 backend; rm backend-image
    - name: Run frontend
      # env:
      #   SSH_KEY: ${{ secrets.SSH_KEY }}
      uses: appleboy/ssh-action@master
      with:
        host: 129.154.230.82
        username: ubuntu
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: 
          # scp -i $SSH_KEY frontend-image ubuntu@129.154.230.82:~/
          docker load < frontend-image.tar; docker stop frontend; docker rm frontend; docker run --name frontend -d -p 80:80 frontend; rm frontend-image