name: Build and deploy app

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  push_frontend_to_registry:
      name: Push frontend docker image to Docker Hub
      runs-on: ubuntu-latest
      steps:
        - name: Check out the repo
          uses: actions/checkout@v2

        - name: Log in to Docker Hub
          uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Extract metadata (tags, labels) for Docker
          id: meta
          uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
          with:
            images: lbsdocker1/frontend

        - name: Build and push Docker image
          uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
          with:
            context: frontend/
            push: true
            file: frontend/Dockerfile
            tags: ${{ github.sha }}
            labels: frontend
  
  push_backend_to_registry:
      name: Push backend docker image to Docker Hub
      runs-on: ubuntu-latest
      steps:
        - name: Check out the repo
          uses: actions/checkout@v2

        - name: Log in to Docker Hub
          uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Extract metadata (tags, labels) for Docker
          id: meta
          uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
          with:
            images: lbsdocker1/backend

        - name: Build and push Docker image
          uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
          with:
            context: backend/
            push: true
            file: backend/Dockerfile
            tags: ${{ github.sha }}
            labels: backend

  run_app:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
#     - name: Build frontend Docker image
#       run: |
#         docker build frontend/ --file frontend/Dockerfile --tag frontend
#         docker save -o frontend-image.tar frontend
#     - name: Build backend Docker image
#       run: |
#         docker build backend/ --file backend/Dockerfile --tag backend
#         docker save -o backend-image.tar backend
#     - name: Copy docker image to backend
#       uses: appleboy/scp-action@master
#       with:
#         host: 150.230.232.20
#         username: ubuntu
#         key: ${{ secrets.SSH_KEY }}
#         port: 22
#         source: "backend-image.tar"
#         target: "~/"
#     - name: Copy docker image to frontend
#       uses: appleboy/scp-action@master
#       with:
#         host: 129.154.230.82
#         username: ubuntu
#         key: ${{ secrets.SSH_KEY }}
#         port: 22
#         source: "frontend-image.tar"
#         target: "~/"
    - name: Run backend
      # env:
      #   SSH_KEY: ${{ secrets.SSH_KEY }}
      uses: appleboy/ssh-action@master
      with:
        host: 150.230.232.20
        username: ubuntu
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: 
#           scp -i $SSH_KEY backend-image ubuntu@150.230.232.20:~/
#           docker load < backend-image.tar; docker stop backend || true; docker rm backend || true; docker run --name backend -d -p 80:8080 backend; rm backend-image.tar
          echo ${{ secrets.DOCKER_USERNAME }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin; docker stop backend || true; docker rm backend || true; docker run --name backend -d -p 80:8080 lbsdocker1/backend:${{ github.sha }}; 
    - name: Run frontend
      # env:
      #   SSH_KEY: ${{ secrets.SSH_KEY }}
      uses: appleboy/ssh-action@master
      with:
        host: 129.154.230.82
        username: ubuntu
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: 
#           scp -i $SSH_KEY frontend-image ubuntu@129.154.230.82:~/
#           docker load < frontend-image.tar; docker stop frontend || true; docker rm frontend || true; docker run --name frontend -d -p 80:80 frontend; rm frontend-image.tar
          echo ${{ secrets.DOCKER_USERNAME }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin; docker stop frontend || true; docker rm frontend || true; docker run --name frontend -d -p 80:8080 lbsdocker1/frontend:${{ github.sha }}; 

