name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build frontend Docker image
      run: docker build frontend/ --file frontend/Dockerfile --tag frontend:$(date +%s)
      run: docker save frontend frontend:$(date +%s)
    - name: Build backend Docker image
      run: docker build backend/ --file backend/Dockerfile --tag backend:$(date +%s)
      run: docker save backend backend:$(date +%s)
    - name: Run backend
      run: scp -i $SSH_KEY backend ubuntu@150.230.232.20:~/
      run: ssh -i $SSH_KEY ubuntu@150.230.232.20 "docker import backend backend:$(date +%s); docker run -d -p 80:8080 backend:$(date +%s); rm backend"
    - name: Run frontend
      run: scp -i $SSH_KEY frontend ubuntu@129.154.230.82:~/
      run: ssh -i $SSH_KEY ubuntu@129.154.230.82 "docker import frontend frontend:$(date +%s); docker run -d -p 80:8080 frontend:$(date +%s); rm frontend"
