name: Build and deploy app

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build frontend Docker image
      run: |
        docker build frontend/ --file frontend/Dockerfile --tag frontend
        docker save -o frontend-image frontend
    - name: Build backend Docker image
      run: |
        docker build backend/ --file backend/Dockerfile --tag backend
        docker save -o backend-image backend
    - name: Run backend
      with:
        SSH_KEY: ${{ secrets.SSH_KEY }}
      run: |
        scp -i $SSH_KEY backend-image ubuntu@150.230.232.20:~/
        ssh -i $SSH_KEY ubuntu@150.230.232.20 "docker import backend-image backend; docker stop backend; docker rm backend; docker run --name backend -d -p 80:8080 backend; rm backend-image"
    - name: Run frontend
      with:
        SSH_KEY: ${{ secrets.SSH_KEY }}
      run: |
        scp -i $SSH_KEY frontend-image ubuntu@129.154.230.82:~/
        ssh -i $SSH_KEY ubuntu@129.154.230.82 "docker import frontend-image frontend; docker stop frontend; docker rm frontend; docker run --name frontend -d -p 80:80 frontend; rm frontend-image"
    - name: Delete saved Docker images from hosted agent
      run: rm frontend-image backend-image